# cocotb stub Makefile for core_pe.sv — cf04 COPT Part B

SIM            = icarus
TOPLEVEL_LANG  = verilog
VERILOG_SOURCES = $(PWD)/core_pe.sv
TOPLEVEL       = core_pe
MODULE         = test_pe

COMPILE_ARGS  += -g2012

include $(shell cocotb-config --makefiles)/Makefile.sim
